server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://192.168.2.23:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  elasticsearch:
    rest:
      uris: http://localhost:9200

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml

